import { createContext, useContext, useState, type ReactNode } from "react";
import { Link, useRouterState } from "@tanstack/react-router";
import { Mail, ClipboardList, CalendarCheck, Workflow, Loader2, ShieldAlert } from "lucide-react";
import { cn } from "@/lib/utils";

// Centralized loading state: any tool can register itself as "generating"
// and the header shows a global spinner indicator.
const LoadingContext = createContext<{
  generating: boolean;
  setGenerating: (v: boolean) => void;
}>({ generating: false, setGenerating: () => {} });

export function useGenerating() {
  return useContext(LoadingContext);
}

const NAV_ITEMS = [
  { to: "/smart-email", label: "Smart Email", icon: Mail },
  { to: "/meeting-summarizer", label: "Meeting Summarizer", icon: ClipboardList },
  { to: "/task-planner", label: "Task Planner", icon: CalendarCheck },
] as const;

export function AppLayout({ children }: { children: ReactNode }) {
  const [generating, setGenerating] = useState(false);
  const pathname = useRouterState({ select: (s) => s.location.pathname });

  return (
    <LoadingContext.Provider value={{ generating, setGenerating }}>
      <div className="flex min-h-screen bg-background">
        {/* Left sidebar */}
        <aside className="sticky top-0 flex h-screen w-64 shrink-0 flex-col border-r border-border bg-sidebar">
          <Link to="/" className="flex items-center gap-2.5 border-b border-border px-5 py-5">
            <span className="flex h-9 w-9 items-center justify-center rounded-lg bg-primary text-primary-foreground">
              <Workflow className="h-5 w-5" />
            </span>
            <span className="text-lg font-semibold tracking-tight text-foreground">WorkFlow AI</span>
          </Link>
          <nav className="flex-1 space-y-1 p-3">
            {NAV_ITEMS.map(({ to, label, icon: Icon }) => {
              const active = pathname.startsWith(to);
              return (
                <Link
                  key={to}
                  to={to}
                  className={cn(
                    "flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-medium transition-colors",
                    active
                      ? "bg-sidebar-accent text-sidebar-accent-foreground"
                      : "text-muted-foreground hover:bg-secondary hover:text-foreground",
                  )}
                >
                  <Icon className="h-4 w-4" />
                  {label}
                </Link>
              );
            })}
          </nav>
          <div className="border-t border-border p-4 text-xs text-muted-foreground">
            Automate the busywork. Keep the judgment.
          </div>
        </aside>

        {/* Main column */}
        <div className="flex min-w-0 flex-1 flex-col">
          {/* Top header */}
          <header className="sticky top-0 z-10 border-b border-border bg-card">
            <div className="flex items-center justify-between px-6 py-3">
              <h1 className="text-base font-semibold text-foreground">WorkFlow AI</h1>
              <div className="flex items-center gap-2 text-sm text-muted-foreground">
                {generating && (
                  <span className="flex items-center gap-2 text-primary">
                    <Loader2 className="h-4 w-4 animate-spin" />
                    Generating…
                  </span>
                )}
              </div>
            </div>
            {/* Responsible AI disclaimer banner */}
            <div className="flex items-center gap-2 border-t border-border bg-accent px-6 py-2 text-xs text-accent-foreground">
              <ShieldAlert className="h-3.5 w-3.5 shrink-0" />
              <p>
                AI outputs are generated by models and may contain errors or biases. Always review
                and validate content before professional use.
              </p>
            </div>
          </header>

          <main className="flex-1 px-6 py-8">{children}</main>
        </div>
      </div>
    </LoadingContext.Provider>
  );
}
